gui:
    scrollHeight: 2
    scrollPastBottom: true
    scrollOffMargin: 2
    scrollOffBehavior: margin
    tabWidth: 4
    mouseEvents: true
    skipAmendWarning: false
    skipDiscardChangeWarning: false
    skipStashWarning: false
    skipNoStagedFilesWarning: false
    skipRewordInEditorWarning: false
    skipSwitchWorktreeOnCheckoutWarning: false
    sidePanelWidth: 0.4
    expandFocusedSidePanel: true
    expandedSidePanelWeight: 3
    mainPanelSplitMode: flexible
    enlargedSideViewLocation: left
    wrapLinesInStagingView: true
    useHunkModeInStagingView: true
    commitLength:
        show: true
    showListFooter: true
    showFileTree: true
    showRootItemInFileTree: false
    showNumstatInFilesView: false
    showRandomTip: false
    showCommandLog: false
    showBottomLine: true
    showPanelJumps: true
    showIcons: true
    nerdFontsVersion: ""
    showFileIcons: true
    commitAuthorShortLength: 2
    commitAuthorLongLength: 17
    commitHashLength: 8
    showBranchCommitHash: false
    showDivergenceFromBaseBranch: none
    commandLogSize: 8
    splitDiff: auto
    screenMode: normal
    border: rounded
    animateExplosion: true
    portraitMode: auto
    filterMode: substring
    statusPanelView: dashboard
    switchToFilesAfterStashPop: true
    switchToFilesAfterStashApply: true
    switchTabsWithPanelJumpKeys: false
    theme:
      activeBorderColor:
        - '#89b4fa'
        - bold
      inactiveBorderColor:
        - '#a6adc8'
      optionsTextColor:
        - '#89b4fa'
      selectedLineBgColor:
        - '#313244'
      cherryPickedCommitBgColor:
        - '#45475a'
      cherryPickedCommitFgColor:
        - '#89b4fa'
      unstagedChangesColor:
        - '#f38ba8'
      defaultFgColor:
        - '#cdd6f4'
      searchingActiveBorderColor:
        - '#f9e2af'

    authorColors:
      '*': '#b4befe'
git:
    diffCommand: "delta --dark --paging=always"
    fzfIntegration: true
    pagers: []
    commit:
        signOff: true
        gpgSign: true
        autoWrapCommitMessage: true
        autoWrapWidth: 72
    merging:
        manualCommit: false
        args: ""
        squashMergeMessage: Squash merge {{selectedRef}} into {{currentBranch}}
    mainBranches:
        - master
        - main
    skipHookPrefix: WIP
    autoFetch: true
    autoRefresh: true
    autoForwardBranches: onlyMainBranches
    fetchAll: true
    autoStageResolvedConflicts: true
    branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
    allBranchesLogCmds:
        - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium
    ignoreWhitespaceInDiffView: false
    diffContextSize: 3
    renameSimilarityThreshold: 50
    overrideGpg: false
    disableForcePushing: false
    commitPrefix: []
    commitPrefixes: {}
    branchPrefix: ""
    parseEmoji: false
    log:
        order: topo-order
        showGraph: always
    showWholeGraph: false
    localBranchSortOrder: date
    remoteBranchSortOrder: date
    truncateCopiedCommitHashesTo: 12
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme base16-256 -s
update:
    method: prompt
    days: 14
refresher:
    refreshInterval: 10
    fetchInterval: 60
confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: false
customCommands: []
services: {}
notARepository: prompt
promptToReturnFromSubprocess: false

